- name: Create Azure Container Registry
  hosts: localhost
  connection: local
  tasks:
    - name: Log into Azure
      shell: "az login"
    - name: Create Resource Group
      shell: "az group create --name WhanosRG --location francecentral"
    - name: Create service principal
      shell: "az ad sp create-for-rbac --name WhanosSP --role owner --scopes /subscriptions/$(az account show --query id -o tsv)/resourceGroups/WhanosRG > tmp.json"
    - name: Fill .env file
      shell: "sed -i \"1 i SUBSCRIPTION_ID=$subscriptionID\nAPP_ID=$(grep -oP '(?<=\"appId\": \")[^\"]*' tmp.json)\nPASSWORD=$(grep -oP '(?<=\"password\": \")[^\"]*' tmp.json)\nTENANT_ID=$(grep -oP '(?<=\"tenant\": \")[^\"]*' tmp.json)\" .env && rm tmp.json"
    - name: Creation of Azure Container Registry
      azure_rm_containerregistry:
        name: "WhanosRegistry"
        resource_group: "WhanosRG"
        location: "francecentral"
        admin_user_enabled: true
        sku: "standard"
        tags:
          environment: "dev"
        env:
          subscription_id: "{{ lookup('env', 'SUBSCRIPTION_ID') }}"
          client_id: "{{ lookup('env', 'APP_ID') }}"
          secret: "{{ lookup('env', 'PASSWORD') }}"
          tenant: "{{ lookup('env', 'TENANT_ID') }}"
        subscription_id: "{{ subscription_id }}"
        client_id: "{{ client_id }}"
        secret: "{{ secret }}"
        tenant: "{{ tenant }}"
      register: acr

- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  tasks:
    - name: Creation of Azure Kubernetes Service
      azure_rm_kubernetes:
        name: "WhanosK8S"
        resource_group: "WhanosRG"
        location: "francecentral"
        dns_name_prefix: "whanos"
        agent_pool_profiles:
          - name: default
            count: 2
            vm_size: "Standard_B2s"
        env:
          subscription_id: "{{ lookup('env', 'SUBSCRIPTION_ID') }}"
          client_id: "{{ lookup('env', 'APP_ID') }}"
          secret: "{{ lookup('env', 'PASSWORD') }}"
          tenant: "{{ lookup('env', 'TENANT_ID') }}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ secret }}"
        tags:
          environment: "dev"
        subscription_id: "{{ subscription_id }}"
        client_id: "{{ client_id }}"
        secret: "{{ secret }}"
        tenant: "{{ tenant }}"
        container_registry_name: "WhanosRegistry"
        container_registry_resource_group: "WhanosRG"
        container_registry_login_server: "whanosregistry.azurecr.io"
      register: aks

- name: Deploy Jenkins Instance
  hosts: localhost
  connection: local
  tasks:
    - name: Log into Azure
      env:
        client_id: "{{ lookup('env', 'APP_ID') }}"
        secret: "{{ lookup('env', 'PASSWORD') }}"
        tenant: "{{ lookup('env', 'TENANT_ID') }}"
      shell: "az login --service-principal -u {{ client_id }} -p {{ secret }} --tenant {{ tenant }}"
    - name: Push into Azure
      shell: "az acr build --image jenkins-whanos:latest --registry WhanosRegistry --file jenkins/Dockerfile ."
    - name: Install kubectl interface
      shell: "az aks install-cli"
    - name: Get credentials WhanosK8S
      shell: "az aks get-credentials --resource-group WhanosRG --name WhanosK8S"
    - name: Deploy jenkins
      shell: "kubectl apply -f jenkins/jenkins_deployment.yaml"
    - name: Print Jenkins's dns name
      shell: ""
