version: "3.8"

services:
  jenkins:
    build: .
    image: jenkins:whanos
    restart: unless-stopped
    env_file:
      - jenkins/env_variable.txt
    ports:
      - 8080:8080
    container_name: jenkins
    depends_on:
      - dind
  dind:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    ports:
      - 2375:2375
    environment:
      - DOCKER_TLS_CERTDIR=