FROM maven:latest AS build
SHELL [ "/bin/bash", "-c" ]
ONBUILD WORKDIR /app
ONBUILD COPY app/. .
ONBUILD RUN mvn dependency:go-offline -B
ONBUILD RUN mvn package

FROM eclipse-temurin:latest
SHELL [ "/bin/bash", "-c" ]
ONBUILD WORKDIR /app
ONBUILD COPY --from=build /app/target/app.jar /app/app.jar
ONBUILD CMD [ "java", "-jar", "/app.jar" ]