FROM maven:3.8.7-eclipse-temurin-17
SHELL [ "/bin/bash", "-c" ]
WORKDIR /app
COPY app/. .
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
RUN mvn package
RUN mv target/app app.jar && rm -r target/ && rm pom.xml
CMD [ "java", "-jar", "app.jar" ]