FROM maven:latest AS build
SHELL [ "/bin/bash", "-c" ]
WORKDIR /app
COPY app/. .
RUN mvn dependency:go-offline -B
RUN mvn package

FROM eclipse-temurin:latest
SHELL [ "/bin/bash", "-c" ]
WORKDIR /app
COPY --from=build /app/target/app.jar /app/app.jar
CMD [ "java", "-jar", "/app.jar" ]