FROM maven:3.8.7-eclipse-temurin-17
SHELL [ "/bin/bash", "-c" ]
ONBUILD WORKDIR /app
ONBUILD COPY app/. .
ONBUILD RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
ONBUILD RUN mvn package
ONBUILD RUN mv target/app.jar app.jar && rm -r target/ && rm pom.xml && rm -r src/
ONBUILD CMD [ "java", "-jar", "app.jar" ]