jenkins:
  systemMessage: "impressive WHANOS"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: ${USER_ADMIN_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos Admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

unclassified:
  location:
    url: http://jenkins:8080/
jobs:
  - file: "/jenkins/job_dsl.groovy"
