apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-instance
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins-instance
  template:
    metadata:
      labels:
        app: jenkins-instance
    spec:
      containers:
      - name: jenkins-instance-container
        image: whanosregistry.azurecr.io/jenkins-whanos:latest
        envFrom:
          - secretRef:
              name: jenkins-secrets
        resources:
          limits:
            memory: "7Gi"
            cpu: "500m"
          requests:
            memory: "5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: jenkins-port
      - name: dind-container
        image: docker:dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        resources:
          limits:
            memory: "5Gi"
            cpu: "500m"
          requests:
            memory: "3Gi"
            cpu: "500m"
        ports:
        - containerPort: 2375
          name: dind-port
        securityContext:
          privileged: true

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance
spec:
  type: LoadBalancer
  selector:
    app: jenkins-instance
  ports:
  - port: 80
    targetPort: jenkins-port

---

apiVersion: v1
kind: Service
metadata:
  name: dind-jenkins-instance
spec:
  selector:
    app: jenkins-instance
  ports:
  - port: 2375
    targetPort: dind-port
