FROM python:latest
SHELL [ "/bin/bash", "-c" ]
ONBUILD WORKDIR /app
ONBUILD COPY requirements.txt .
ONBUILD RUN pip install --no-cache-dir -r requirements.txt
ONBUILD COPY . .
ONBUILD CMD [ "python", "-m", "app" ]